name: Docker Build and Push to ECR

on:
  workflow_dispatch:

# on:
#     push:
#         branches:
#             - blahblahblah


jobs:
    All_In_One:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: "./Docker/app/"
        steps:
            - name: Checkout
              uses: actions/checkout@v4


            - name: Login to AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}


            - name: Login to AWS ECR
              uses: docker/login-action@v3
              with:
                registry: ${{ secrets.AWS_REGISTRY }}

                username: ${{ secrets.AWS_ACCESS_KEY }}
                password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              env:
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Build and Push to ECR
              run: |
                docker build -t threat-composer-tool .
                docker tag threat-composer-tool:latest ${{ secrets.AWS_REGISTRY }}/threat-composer-tool:latest
                docker push ${{ secrets.AWS_REGISTRY }}/threat-composer-tool:latest

        