name: Terraform Checkov & Tflint

# on:
#   workflow_dispatch:

on:
    push:
        branches:
            - test


jobs:
    terraformapply:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: "./Terraform/"
        environment: aws
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Checkov GitHub Action
              uses: bridgecrewio/checkov-action@master
              with:
                output_format: cli,sarif
                output_file_path: console,results.sarif
              
            - name: Upload SARIF file
              uses: github/codeql-action/upload-sarif@v3
              if: success() || failure()
              with:
                sarif_file: 'trivy-results-Docker.sarif'
                wait-for-processing: true