name: Terraform Checkov & Tflint

# on:
#   workflow_dispatch:

on:
    push:
        branches:
            - test


jobs:
    terraformapply:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: "./Terraform/"
        permissions:
            security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Tflint
              uses: terraform-linters/setup-tflint@master
              with: 
                tflint_version: latest

            - name: TFlint Scan   #See this link for command flags https://github.com/terraform-linters/tflint
              run: |
                tflint --init
                tflint --recursive -f sarif
                ls -la
              continue-on-error: true

            - name: Upload TFLint scan results to GitHub Security tab
              uses: github/codeql-action/upload-sarif@v3
              if: success() || failure()
              with:
                sarif_file: 'tflint-results-terraform.sarif'
                wait-for-processing: true
      

            - name: Checkov
              uses: bridgecrewio/checkov-action@master
              with:
                framework: terraform
                soft_fail: false
                output_format: cli,sarif
                output_file_path: checkov-results-terraform.sarif
              
            - name: Upload Checkov scan results to GitHub Security tab
              uses: github/codeql-action/upload-sarif@v3
              if: success() || failure()
              with:
                sarif_file: 'checkov-results-terraform.sarif'
                wait-for-processing: true