name: Terraform Checkov & Tflint

# on:
#   workflow_dispatch:

on:
    push:
        branches:
            - test


jobs:
    terraformapply:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: "./Terraform/"
        permissions:
            contents: read # for actions/checkout to fetch code
            security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Tflint
              uses: terraform-linters/setup-tflint@v4
              with: 
                tflint_version: latest

            - name: TFlint Scan
              run: tflint

            - name: Checkov GitHub Action
              uses: bridgecrewio/checkov-action@master
              with:
                framework: terraform
                soft_fail: false
                output_format: cli,sarif
                output_file_path: checkov-results-terraform.sarif
              
            - name: Upload SARIF file
              uses: github/codeql-action/upload-sarif@v3
              if: success() || failure()
              with:
                sarif_file: 'checkov-results-terraform.sarif'
                wait-for-processing: true